(()=>{
 if(window.__deenV789Applied)return;window.__deenV789Applied=true;
 const VERSION='7.8.9',STATE_VERSION=62;
 window.DEEN_RELEASE_VERSION=VERSION;document.title='DEEN v7.8.9 — Try Before Buy / Oda Önizleme';
 const WORLD=window.DEEN_WORLD,COLLECTION=window.DEEN_WORLD_COLLECTION,DECOR=window.DEEN_WORLD_DECOR,PROG=window.DEEN_WORLD_PROGRESSION,IDLE=window.DEEN_WORLD_IDLE,ACTIONS=window.DEEN_WORLD_ACTIONS;
 if(!WORLD||!COLLECTION)return;
 const OLD_CLASS={desk_sand:'v787-desk-sand',rug_sunrise:'v787-rug-sunrise',plant_olive:'v787-plant-olive',shelf_oak:'v787-shelf-oak',window_night:'v787-window-night',nur_starlight:'v787-nur-starlight'};
 const TYPE_LABEL={desk:'Masa',rug:'Halı',plant:'Bitki',shelf:'Kitaplık',window:'Pencere',nur:'NUR'};
 const TYPE_TARGET={desk:'.v750-obj-desk',rug:'.v750-obj-rug',plant:'.v750-obj-plant',shelf:'.v750-obj-shelf',window:'.v779-window-scene',nur:'.v750-obj-nur'};
 let scheduled=false,currentId=null;
 function items(){try{return COLLECTION.items?.()||[]}catch(e){return[]}}
 function item(id){return items().find(x=>x.id===id)||null}
 function owned(id){return !!state.myWorld?.owned?.includes?.(id)}
 function level(){try{return Number(PROG?.snapshot?.().level)||1}catch(e){return 1}}
 function rarity(r){return r==='epic'?'EPIC':r==='rare'?'RARE':'COMMON'}
 function sanitizeClone(root){root.removeAttribute('id');root.querySelectorAll('[id]').forEach(el=>el.removeAttribute('id'));root.querySelectorAll('.v782-action-chip,.v783-ambient-spark,.v785-room-reveal').forEach(el=>el.remove());root.querySelectorAll('[contenteditable]').forEach(el=>el.removeAttribute('contenteditable'))}
 function removeTypeClasses(r,type){const prefixes=['v787-'+type+'-','v788-eq-'+type+'_'];[...r.classList].forEach(c=>{if(prefixes.some(p=>c.startsWith(p)))r.classList.remove(c)});if(type==='plant')r.classList.remove('v787-no-plant');if(type==='shelf')r.classList.remove('v787-no-shelf')}
 function applyPreviewClass(r,x){removeTypeClasses(r,x.type);const cls=OLD_CLASS[x.id]||('v788-eq-'+x.id);r.classList.add(cls,'v789-preview-room','v789-preview-'+x.type);r.dataset.v789Preview=x.id;const t=r.querySelector(TYPE_TARGET[x.type]);if(t){t.style.display='';t.style.visibility='visible';t.style.opacity='1'}}
 function buttonState(x){if(owned(x.id))return{label:'ODADA KULLAN',cls:'',disabled:false,mode:'use'};if(level()<(Number(x.req)||1))return{label:'🔒 ODA LV '+(Number(x.req)||1),cls:'',disabled:true,mode:'locked'};return{label:'🪙 '+(Number(x.price)||0)+' · SATIN AL',cls:'buy',disabled:false,mode:'buy'}}
 function close(reason='cancel'){const o=document.querySelector('#worldScreenBody .v789-preview');if(!o)return false;o.remove();document.body.classList.remove('v789-preview-open');const id=currentId;currentId=null;try{IDLE?.reschedule?.()}catch(e){};if(reason==='cancel'&&id)try{DEEN_SFX?.play?.('tap')}catch(e){};return true}
 function open(id){const x=item(id),scope=document.getElementById('worldScreenBody'),room=document.getElementById('v750Room');if(!x||!scope||!room)return false;close('replace');currentId=id;try{ACTIONS?.clear?.()}catch(e){};try{IDLE?.clear?.()}catch(e){};const clone=room.cloneNode(true);sanitizeClone(clone);applyPreviewClass(clone,x);const bs=buttonState(x),o=document.createElement('div');o.className='v789-preview';o.setAttribute('role','dialog');o.setAttribute('aria-modal','true');o.innerHTML=`<div class="v789-preview-top"><div class="v789-preview-title"><small>ÖNİZLEME · KAYDEDİLMEZ</small><b>${x.name}</b></div><button class="v789-preview-close" type="button" aria-label="Kapat">×</button></div><div class="v789-preview-stage"><div class="v789-preview-room-shell"></div></div><div class="v789-preview-info"><div class="v789-preview-meta"><span class="v789-preview-icon">${x.icon||'✦'}</span><span class="v789-preview-copy"><b>${x.name}</b><small>${TYPE_LABEL[x.type]||x.type} · Oda LV ${Number(x.req)||1} · <span class="v788-rarity ${x.rarity||'common'}">${rarity(x.rarity)}</span></small></span><span class="v789-preview-price">${owned(x.id)?'SAHİPSİN':'🪙 '+(Number(x.price)||0)}</span></div><div class="v789-preview-actions"><button type="button" class="v789-cancel">VAZGEÇ</button><button type="button" class="v789-confirm ${bs.cls}" data-v789-mode="${bs.mode}" ${bs.disabled?'disabled':''}>${bs.label}</button></div><div class="v789-preview-note"><b>Bu yalnızca görsel önizlemedir.</b> Vazgeçersen mevcut odan ve Altın bakiyen değişmez.</div></div>`;o.querySelector('.v789-preview-room-shell')?.append(clone);scope.append(o);document.body.classList.add('v789-preview-open');o.querySelector('.v789-preview-close')?.addEventListener('click',()=>close('cancel'));o.querySelector('.v789-cancel')?.addEventListener('click',()=>close('cancel'));o.addEventListener('click',e=>{if(e.target===o)close('cancel')});o.querySelector('.v789-confirm')?.addEventListener('click',()=>confirm(id));try{DEEN_SFX?.play?.('snap')}catch(e){};return true}
 function confirm(id){const x=item(id);if(!x)return false;if(owned(id)){const ok=COLLECTION.equip?.(id)!==false;if(ok){close('use');toast?.(x.name+' odada kullanılıyor')}return ok}if(level()<(Number(x.req)||1))return false;const before=owned(id),res=WORLD.buy?.(id);setTimeout(()=>{if(owned(id)&&!before){try{COLLECTION.equip?.(id)}catch(e){};close('buy');toast?.(x.name+' odana uygulandı')}},120);return res!==false}
 function decorateCards(){scheduled=false;const map=new Map(items().map(x=>[x.name,x]));document.querySelectorAll('#worldScreenBody .v788-card').forEach(card=>{if(card.querySelector(':scope > .v789-try'))return;const name=card.querySelector('h3')?.textContent?.trim(),x=map.get(name);if(!x||card.classList.contains('equipped'))return;const b=document.createElement('button');b.type='button';b.className='v789-try';b.dataset.v789Preview=x.id;b.textContent=card.classList.contains('locked')?'ÖNİZLE':'ODADA DENE';const primary=[...card.children].find(el=>el.tagName==='BUTTON'&&!el.classList.contains('v789-try'));if(primary)card.insertBefore(b,primary);else card.append(b)})}
 function schedule(ms=50){if(scheduled)return;scheduled=true;setTimeout(decorateCards,ms)}
 document.addEventListener('click',e=>{const b=e.target.closest?.('[data-v789-preview]');if(!b)return;e.preventDefault();e.stopPropagation();open(b.dataset.v789Preview)},true);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('#worldScreenBody .v789-preview'))close('cancel')});
 const obs=new MutationObserver(ms=>{for(const m of ms){if(m.type==='childList'&&m.target?.closest?.('#worldScreenBody')){schedule(45);break}}});obs.observe(document.body,{childList:true,subtree:true});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)close('hidden');else schedule(120)});window.addEventListener('pagehide',()=>close('hidden'));
 state.stateVersion=Math.max(STATE_VERSION,Number(state.stateVersion)||0);try{saveState?.()}catch(e){}
 window.DEEN_WORLD_PREVIEW={version:VERSION,stateVersion:STATE_VERSION,open,close,refresh:decorateCards,snapshot:()=>({version:VERSION,open:!!document.querySelector('#worldScreenBody .v789-preview'),item:currentId,tryButtons:document.querySelectorAll('#worldScreenBody .v789-try').length,gold:Number(state.currency)||0,equipped:{...(state.myWorld?.equipped||{})}})};
 setTimeout(()=>decorateCards(),650);
})();
