(()=>{
 if(window.__deenV788Applied)return;window.__deenV788Applied=true;
 const VERSION='7.8.8',STATE_VERSION=61;
 window.DEEN_RELEASE_VERSION=VERSION;document.title='DEEN v7.8.8 — Decor Collection & Rarity Shop';
 const WORLD=window.DEEN_WORLD,DECOR=window.DEEN_WORLD_DECOR,PROG=window.DEEN_WORLD_PROGRESSION,IW=window.DEEN_INTERACTIVE_WORLD;
 if(!WORLD||!DECOR)return;
 const NEW_ITEMS=[
  {id:'desk_walnut',type:'desk',name:'Ceviz Çalışma Masası',icon:'▰',price:45,rarity:'common',req:1,desc:'Koyu ahşap, sade çalışma masası.'},
  {id:'desk_sage',type:'desk',name:'Adaçayı Masası',icon:'▰',price:85,rarity:'rare',req:3,desc:'Yumuşak yeşil, sakin odak teması.'},
  {id:'desk_celestial',type:'desk',name:'Gökyüzü Masası',icon:'✦',price:150,rarity:'epic',req:6,desc:'Gece tonları ve ince yıldız detayları.'},
  {id:'rug_moss',type:'rug',name:'Yosun Halı',icon:'◉',price:40,rarity:'common',req:1,desc:'Doğal yeşil tonlarda yumuşak halı.'},
  {id:'rug_midnight',type:'rug',name:'Gece Mavisi Halı',icon:'◉',price:90,rarity:'rare',req:3,desc:'Derin lacivert katmanlı oda dokusu.'},
  {id:'rug_constellation',type:'rug',name:'Takımyıldız Halısı',icon:'✧',price:145,rarity:'epic',req:6,desc:'Yıldız noktalarıyla premium gece halısı.'},
  {id:'plant_fern',type:'plant',name:'Eğrelti Saksısı',icon:'♧',price:35,rarity:'common',req:1,desc:'Canlı ve sade yeşil oda bitkisi.'},
  {id:'plant_lavender',type:'plant',name:'Lavanta Saksısı',icon:'♧',price:75,rarity:'rare',req:3,desc:'Mor saksı ve sakin bitki tonları.'},
  {id:'plant_moonbonsai',type:'plant',name:'Ay Bonsaisi',icon:'♧',price:140,rarity:'epic',req:6,desc:'Soğuk tonlu, hafif ışıltılı bonsai.'},
  {id:'shelf_walnut',type:'shelf',name:'Ceviz Kitaplık',icon:'▥',price:55,rarity:'common',req:2,desc:'Koyu ceviz raflarla klasik görünüm.'},
  {id:'shelf_arch',type:'shelf',name:'Kemer Kitaplık',icon:'▥',price:95,rarity:'rare',req:4,desc:'Yuvarlatılmış kemer formunda raf sistemi.'},
  {id:'shelf_celestial',type:'shelf',name:'Gökyüzü Kitaplığı',icon:'✦',price:155,rarity:'epic',req:6,desc:'Lacivert gövde ve altın detaylar.'},
  {id:'window_dawn',type:'window',name:'Şafak Penceresi',icon:'◒',price:60,rarity:'common',req:2,desc:'Odaya sıcak gün doğumu atmosferi verir.'},
  {id:'window_rain',type:'window',name:'Yağmur Penceresi',icon:'∿',price:105,rarity:'rare',req:4,desc:'Serin yağmur çizgileri ve koyu gökyüzü.'},
  {id:'window_crescent',type:'window',name:'Hilal Penceresi',icon:'☾',price:165,rarity:'epic',req:6,desc:'Hilalli gece manzarası ve yıldız dokusu.'},
  {id:'nur_mint',type:'nur',name:'NUR · Mint Işık',icon:'✦',price:50,rarity:'common',req:2,desc:'Mint tonlu sade ışık görünümü.'},
  {id:'nur_amber',type:'nur',name:'NUR · Amber Işık',icon:'✦',price:95,rarity:'rare',req:4,desc:'Sıcak amber ışık ve yumuşak glow.'},
  {id:'nur_aurora',type:'nur',name:'NUR · Aurora',icon:'✧',price:170,rarity:'epic',req:7,desc:'Mint, mavi ve mor katmanlı ışık.'}
 ];
 const NEW=Object.fromEntries(NEW_ITEMS.map(x=>[x.id,x]));
 const EXISTING_META={
   plant_olive:{rarity:'common',req:2,desc:'Zeytin tonlarında doğal saksı.'},shelf_oak:{rarity:'common',req:3,desc:'Sıcak meşe tonlarında kitaplık.'},rug_sunrise:{rarity:'rare',req:4,desc:'Gün doğumu renklerinde sıcak halı.'},desk_sand:{rarity:'rare',req:5,desc:'Kum tonlarında premium çalışma masası.'},window_night:{rarity:'rare',req:6,desc:'Ay ve gece tonlarında pencere.'},nur_starlight:{rarity:'epic',req:7,desc:'Altın yıldız ışığı görünümü.'}
 };
 const TYPES=[['all','TÜM'],['desk','MASA'],['rug','HALI'],['plant','BİTKİ'],['shelf','KİTAPLIK'],['window','PENCERE'],['nur','NUR']];
 const BASES={desk:{id:null,name:'Standart Masa',icon:'▰'},rug:{id:'rug_teal',name:'Teal Halı',icon:'◉'},plant:{id:null,name:'Bitki Yok',icon:'♧'},shelf:{id:null,name:'Kitaplık Yok',icon:'▥'},window:{id:null,name:'Standart Pencere',icon:'◒'},nur:{id:null,name:'Standart NUR',icon:'✦'}};
 let activeCat='all',scheduled=false;
 const oldItems=WORLD.items;
 function baseItems(){try{return typeof oldItems==='function'?oldItems.call(WORLD)||[]:[]}catch(e){return[]}}
 function allItems(){const a=baseItems(),ids=new Set(a.map(x=>x.id));return a.concat(NEW_ITEMS.filter(x=>!ids.has(x.id)))}
 if(typeof oldItems==='function'&&!oldItems.__v788){const fn=function(){return allItems().map(x=>({...x}))};fn.__v788=true;WORLD.items=fn}
 function save(){try{saveState?.()}catch(e){}}
 function level(){try{return Number(PROG?.snapshot?.().level)||1}catch(e){return 1}}
 function owned(id){return !id||id==='rug_teal'||!!state.myWorld?.owned?.includes?.(id)}
 function eq(){state.myWorld=state.myWorld&&typeof state.myWorld==='object'?state.myWorld:{};state.myWorld.equipped=state.myWorld.equipped&&typeof state.myWorld.equipped==='object'?state.myWorld.equipped:{};if(!state.myWorld.equipped.rug)state.myWorld.equipped.rug='rug_teal';return state.myWorld.equipped}
 function item(id){return allItems().find(x=>x.id===id)||null}
 function meta(x){if(!x)return{rarity:'common',req:1,desc:''};return NEW[x.id]||{...x,...(EXISTING_META[x.id]||{rarity:'common',req:1,desc:'Dünyam için kalıcı kozmetik dekor.'})}}
 function decorItems(){return allItems().filter(x=>['desk','rug','plant','shelf','window','nur'].includes(x.type)&&!x.default&&!x.paid)}
 function rarityLabel(r){return r==='epic'?'EPIC':r==='rare'?'RARE':'COMMON'}
 function typeLabel(t){return ({desk:'Masa',rug:'Halı',plant:'Bitki',shelf:'Kitaplık',window:'Pencere',nur:'NUR'})[t]||t}
 function spend(n,id){n=Math.max(0,Math.round(Number(n)||0));state.currency=Math.max(0,Number(state.currency)||0);if(state.currency<n)return false;state.currency-=n;state.myWorld.ledger=Array.isArray(state.myWorld.ledger)?state.myWorld.ledger:[];state.myWorld.ledger.push({at:Date.now(),type:'spend',amount:n,reason:'decor_shop_v788',key:id});if(state.myWorld.ledger.length>120)state.myWorld.ledger=state.myWorld.ledger.slice(-120);return true}
 function equipAny(id){const x=item(id);if(!x||!['desk','rug','plant','shelf','window','nur'].includes(x.type)||!owned(id))return false;const out=DECOR.equip?.(x.type,id);applyThemes(x.type);schedule(50);return out!==false}
 function buyNew(id){const x=NEW[id];if(!x)return null;if(owned(id)){equipAny(id);return true}if(level()<x.req){toast?.('Bu dekor Oda Seviyesi '+x.req+' seviyesinde açılır.');return false}if(!spend(x.price,id)){toast?.('Biraz daha Altın gerekiyor.');return false}state.myWorld.owned=Array.isArray(state.myWorld.owned)?state.myWorld.owned:[];state.myWorld.owned.push(id);save();equipAny(id);try{DEEN_SFX?.play?.('reward')}catch(e){};toast?.(x.name+' alındı · -'+x.price+' Altın');try{updateUI?.()}catch(e){};schedule(120);return true}
 const oldBuy=WORLD.buy;if(typeof oldBuy==='function'&&!oldBuy.__v788){const fn=function(id,...args){if(NEW[id])return buyNew(id);const out=oldBuy.call(this,id,...args);setTimeout(()=>schedule(100),0);return out};fn.__v788=true;WORLD.buy=fn}
 function applyThemes(flashType=null){const r=document.getElementById('v750Room');if(!r)return false;const e=eq();[...r.classList].filter(c=>c.startsWith('v788-eq-')).forEach(c=>r.classList.remove(c));for(const t of ['desk','rug','plant','shelf','window','nur']){const id=e[t];if(NEW[id])r.classList.add('v788-eq-'+id)}r.dataset.v788Equipped=[e.desk||'default',e.rug||'rug_teal',e.plant||'none',e.shelf||'none',e.window||'default',e.nur||'default'].join('|');if(flashType){const sel={desk:'.v750-obj-desk',rug:'.v750-obj-rug',plant:'.v750-obj-plant',shelf:'.v750-obj-shelf',window:'.v779-window-scene',nur:'.v750-obj-nur'}[flashType],el=sel?r.querySelector(sel):null;if(el){el.classList.remove('v788-equip-pop');void el.offsetWidth;el.classList.add('v788-equip-pop');setTimeout(()=>el.classList.remove('v788-equip-pop'),620)}}return true}
 function baseChoice(type){const b=BASES[type],current=(eq()[type]??b.id)===b.id;return `<button type="button" class="v788-equip-choice ${current?'active':''}" data-v788-base="${type}"><span class="v788-equip-ico">${b.icon}</span><span class="v788-equip-copy"><b>${b.name}</b><small><span class="v788-rarity starter">STARTER</span></small></span></button>`}
 function equipChoice(x){const m=meta(x),current=eq()[x.type]===x.id;return `<button type="button" class="v788-equip-choice ${current?'active':''}" data-v788-equip="${x.id}"><span class="v788-equip-ico">${x.icon||'✦'}</span><span class="v788-equip-copy"><b>${x.name}</b><small><span class="v788-rarity ${m.rarity}">${rarityLabel(m.rarity)}</span></small></span></button>`}
 function customizer(){const tray=document.querySelector('#worldScreenBody .v750-tray');if(!tray)return;const editing=(()=>{try{return !!IW?.state?.().editMode}catch(e){return false}})();let box=tray.querySelector(':scope > .v788-customizer');if(!editing){box?.remove();return}const groups=['desk','rug','plant','shelf','window','nur'].map(t=>{const own=decorItems().filter(x=>x.type===t&&owned(x.id));return `<div class="v788-equip-group"><div class="v788-equip-label"><span>${typeLabel(t).toUpperCase()}</span><small>${own.length+(BASES[t].id||BASES[t].id===null?1:0)} seçenek</small></div><div class="v788-equip-options">${baseChoice(t)}${own.map(equipChoice).join('')}</div></div>`}).join('');const html=`<div class="v788-customizer"><div class="v788-customizer-head"><div><b>DEKOR KOLEKSİYONU</b><small>Sahip olduğun parçaları seç; nadirlik yalnızca kozmetiktir.</small></div><button type="button" class="v788-customizer-shop">MAĞAZA</button></div><div class="v788-equip-groups">${groups}</div></div>`;if(box)box.outerHTML=html;else tray.insertAdjacentHTML('afterbegin',html);box=tray.querySelector(':scope > .v788-customizer');box?.querySelectorAll('[data-v788-equip]').forEach(b=>b.addEventListener('click',()=>equipAny(b.dataset.v788Equip)));box?.querySelectorAll('[data-v788-base]').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.v788Base,base=BASES[t];DECOR.equip?.(t,base.id);applyThemes(t);schedule(40)}));box?.querySelector('.v788-customizer-shop')?.addEventListener('click',()=>{try{if(IW?.state?.().editMode)IW.edit?.()}catch(e){};setTimeout(()=>WORLD.tab?.('shop'),80)})}
 function card(x){const m=meta(x),isOwned=owned(x.id),isEq=eq()[x.type]===x.id,locked=!isOwned&&level()<m.req;let btn='';if(isEq)btn='<button disabled>ODADA</button>';else if(isOwned)btn=`<button class="use" data-v788-use="${x.id}">KULLAN</button>`;else if(locked)btn=`<button disabled>🔒 ODA LV ${m.req}</button>`;else btn=`<button class="buy" data-v788-buy="${x.id}">🪙 ${x.price} · AL</button>`;return `<article class="v788-card ${isOwned?'owned':''} ${isEq?'equipped':''} ${locked?'locked':''}" data-v788-type="${x.type}"><div class="v788-card-top"><span class="v788-card-icon">${x.icon||'✦'}</span><span class="v788-rarity ${m.rarity}">${rarityLabel(m.rarity)}</span></div><h3>${x.name}</h3><div class="v788-card-desc">${m.desc}</div><div class="v788-card-meta"><span>${typeLabel(x.type)} · LV ${m.req}</span><span class="gold">${isOwned?'SAHİPSİN':'🪙 '+x.price}</span></div>${btn}</article>`}
 function renderShop(){const heads=[...document.querySelectorAll('#worldScreenBody .v740-world-section-head b')],baseHead=heads.find(x=>(x.textContent||'').trim()==='Dünya Mağazası'),baseSec=baseHead?.closest('.v740-world-section');if(!baseSec){document.querySelector('#worldScreenBody .v788-shop')?.remove();return}baseSec.style.display='none';let sec=document.querySelector('#worldScreenBody .v788-shop');const list=decorItems().filter(x=>activeCat==='all'||x.type===activeCat),total=decorItems().length,own=decorItems().filter(x=>owned(x.id)).length;const html=`<section class="v788-shop"><div class="v788-shop-head"><div><h2>Dekor Koleksiyonu</h2><p>Odan için kalıcı kozmetikler. Common / Rare / Epic etiketleri yalnızca görünüm ve koleksiyon değerini gösterir.</p></div><div class="v788-shop-stat">${own}/${total}<br>SAHİP</div></div><div class="v788-filter-row">${TYPES.map(([id,label])=>`<button type="button" class="v788-filter ${activeCat===id?'active':''}" data-v788-filter="${id}">${label}</button>`).join('')}</div><div class="v788-shop-grid">${list.map(card).join('')}</div><div class="v788-shop-note"><b>Nadirlik güç vermez.</b> Epic bir dekor; ders, enerji, NUR kazanımı veya dinî içerikte avantaj sağlamaz. Sadece odanın görünümünü değiştirir.</div></section>`;if(sec)sec.outerHTML=html;else baseSec.insertAdjacentHTML('beforebegin',html);sec=document.querySelector('#worldScreenBody .v788-shop');sec?.querySelectorAll('[data-v788-filter]').forEach(b=>b.addEventListener('click',()=>{activeCat=b.dataset.v788Filter||'all';renderShop()}));sec?.querySelectorAll('[data-v788-buy]').forEach(b=>b.addEventListener('click',()=>{WORLD.buy?.(b.dataset.v788Buy);setTimeout(renderShop,100)}));sec?.querySelectorAll('[data-v788-use]').forEach(b=>b.addEventListener('click',()=>{equipAny(b.dataset.v788Use);setTimeout(renderShop,70)}))}
 function decorate(){scheduled=false;eq();applyThemes();customizer();renderShop()}
 function schedule(ms=55){if(scheduled)return;scheduled=true;setTimeout(decorate,ms)}
 const observer=new MutationObserver(ms=>{for(const m of ms){for(const n of m.addedNodes){if(n.nodeType===1&&(n.matches?.('.v750-world,.v750-tray,.v740-world-section')||n.querySelector?.('.v750-world,.v750-tray,.v740-world-section'))){schedule(45);return}}}});observer.observe(document.body,{childList:true,subtree:true});
 document.addEventListener('click',e=>{if(e.target.closest?.('#worldScreenBody [data-v780="edit"],#worldScreenBody .v780-area-select,#worldScreenBody .v780-back-btn,.navbtn[data-screen="worldScreen"]'))schedule(100)},true);
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule(120)});window.addEventListener('pageshow',()=>schedule(140));
 state.stateVersion=Math.max(STATE_VERSION,Number(state.stateVersion)||0);state.myWorld=state.myWorld||{};state.myWorld.decorCatalogVersion=VERSION;save();
 window.DEEN_WORLD_COLLECTION={version:VERSION,stateVersion:STATE_VERSION,items:()=>allItems().filter(x=>['desk','rug','plant','shelf','window','nur'].includes(x.type)).map(x=>({...x,...meta(x)})),buy:buyNew,equip:equipAny,apply:applyThemes,refresh:decorate,snapshot:()=>({version:VERSION,level:level(),gold:Number(state.currency)||0,owned:decorItems().filter(x=>owned(x.id)).map(x=>x.id),equipped:{...eq()},newItems:NEW_ITEMS.length,shopCards:document.querySelectorAll('#worldScreenBody .v788-card').length,customizer:!!document.querySelector('#worldScreenBody .v788-customizer')})};
 setTimeout(decorate,820);
})();
