(()=>{
 if(window.__deenV791Applied)return;window.__deenV791Applied=true;
 const VERSION='7.9.1',STATE_VERSION=64;
 window.DEEN_RELEASE_VERSION=VERSION;document.title='DEEN v7.9.1 — Shop & Collection Final Polish';
 const COLLECTION=window.DEEN_WORLD_COLLECTION,PREVIEW=window.DEEN_WORLD_PREVIEW,WORLD=window.DEEN_WORLD;
 if(!COLLECTION||!WORLD)return;
 const TYPES=['desk','rug','plant','shelf','window','nur'];
 const TYPE_LABEL={desk:'MASA',rug:'HALI',plant:'BİTKİ',shelf:'KİTAPLIK',window:'PENCERE',nur:'NUR'};
 const VIEWS=[['all','TÜMÜ'],['buyable','ALINABİLİR'],['owned','SAHİP'],['equipped','ODADA']];
 let view='all',scheduled=false,lastSig='';
 function items(){try{return COLLECTION.items?.().filter(x=>TYPES.includes(x.type)&&!x.default&&!x.paid)||[]}catch(e){return[]}}
 function owned(id){return !!state.myWorld?.owned?.includes?.(id)}
 function equipped(id,type){return state.myWorld?.equipped?.[type]===id}
 function level(){try{return Number(window.DEEN_WORLD_PROGRESSION?.snapshot?.().level)||1}catch(e){return 1}}
 function gold(){return Math.max(0,Number(state.currency)||0)}
 function status(x){if(equipped(x.id,x.type))return'equipped';if(owned(x.id))return'owned';if(level()<(Number(x.req)||1))return'locked';return'buyable'}
 function statusLabel(s){return s==='equipped'?'ODADA':s==='owned'?'SAHİPSİN':s==='buyable'?'ALINABİLİR':'KİLİTLİ'}
 function counts(){const a=items(),out={all:a.length,buyable:0,owned:0,equipped:0};for(const x of a){const s=status(x);if(s==='buyable')out.buyable++;if(s==='owned'||s==='equipped')out.owned++;if(s==='equipped')out.equipped++}return out}
 function categoryCounts(){const out={all:items().length};for(const t of TYPES)out[t]=items().filter(x=>x.type===t).length;return out}
 function overview(){const shop=document.querySelector('#worldScreenBody .v788-shop');if(!shop)return null;let box=shop.querySelector(':scope > .v791-shop-polish'),a=items(),own=a.filter(x=>owned(x.id)).length,pct=a.length?Math.round(own/a.length*100):0,c=counts();const html=`<div class="v791-shop-polish"><div class="v791-shop-overview"><div class="v791-overview-copy"><b>Koleksiyonun · ${own}/${a.length}</b><small>%${pct} tamamlandı · Oda Lv ${level()} · nadirlik yalnızca kozmetik.</small></div><div class="v791-wallet">🪙 ${gold()}<br>ALTIN</div></div><div class="v791-progress"><i style="width:${pct}%"></i></div><div class="v791-view-row">${VIEWS.map(([id,label])=>`<button type="button" class="v791-view ${view===id?'active':''}" data-v791-view="${id}">${label}<span class="count">${c[id]}</span></button>`).join('')}</div></div>`;if(box)box.outerHTML=html;else{const head=shop.querySelector(':scope > .v788-shop-head');head?.insertAdjacentHTML('afterend',html)}return shop.querySelector(':scope > .v791-shop-polish')}
 function decorateFilters(){const cc=categoryCounts();document.querySelectorAll('#worldScreenBody .v788-filter').forEach(b=>{const id=b.dataset.v788Filter||'all';let counter=b.querySelector('.v791-filter-count');if(!counter){counter=document.createElement('span');counter.className='v791-filter-count';b.append(counter)}counter.textContent=String(cc[id]??0)})}
 function cardItem(card){const name=card.querySelector('h3')?.textContent?.trim();return items().find(x=>x.name===name)||null}
 function normalizeButtons(card,s,x){const tryBtn=card.querySelector('.v789-try'),buy=card.querySelector('[data-v788-buy]'),use=card.querySelector('[data-v788-use]');if(tryBtn)tryBtn.textContent=s==='locked'?'ÖNİZLE':'ODADA DENE';if(buy)buy.textContent='🪙 '+(Number(x.price)||0)+' · SATIN AL';if(use)use.textContent='ODADA KULLAN';const disabled=[...card.children].find(el=>el.tagName==='BUTTON'&&el.disabled&&!el.classList.contains('v789-try'));if(disabled){if(s==='equipped')disabled.textContent='✓ ŞU AN ODADA';else if(s==='locked')disabled.textContent='🔒 ODA LV '+(Number(x.req)||1)}}
 function decorateCard(card){const x=cardItem(card);if(!x)return;const s=status(x);card.dataset.v791Status=s;card.querySelector(':scope > .v791-state')?.remove();const pill=document.createElement('span');pill.className='v791-state '+s;pill.textContent=statusLabel(s);card.prepend(pill);card.classList.toggle('v791-previewable',s!=='equipped');card.setAttribute('aria-label',x.name+' · '+statusLabel(s));if(s!=='equipped'){card.setAttribute('role','button');card.tabIndex=0}else{card.removeAttribute('role');card.removeAttribute('tabindex')}normalizeButtons(card,s,x);const show=view==='all'||(view==='owned'&&(s==='owned'||s==='equipped'))||view===s;card.classList.toggle('v791-hidden',!show)}
 function emptyState(){const grid=document.querySelector('#worldScreenBody .v788-shop-grid');if(!grid)return;grid.querySelector(':scope > .v791-empty')?.remove();if([...grid.querySelectorAll(':scope > .v788-card')].some(c=>!c.classList.contains('v791-hidden')))return;const e=document.createElement('div');e.className='v791-empty';e.innerHTML='<b>Bu görünümde dekor yok.</b>Başka bir durum filtresi veya kategori seçebilirsin.';grid.append(e)}
 function decorate(force=false){scheduled=false;const shop=document.querySelector('#worldScreenBody .v788-shop');if(!shop)return false;const cards=[...shop.querySelectorAll('.v788-card')],filters=[...shop.querySelectorAll('.v788-filter')],sig=JSON.stringify({view,gold:gold(),level:level(),owned:items().filter(x=>owned(x.id)).map(x=>x.id),eq:state.myWorld?.equipped||{},cards:cards.map(x=>x.querySelector('h3')?.textContent||'')});const complete=!!shop.querySelector(':scope > .v791-shop-polish')&&cards.length>0&&cards.every(c=>c.dataset.v791Status&&c.querySelector(':scope > .v791-state'))&&filters.every(b=>b.querySelector('.v791-filter-count'));if(!force&&sig===lastSig&&complete)return true;lastSig=sig;overview();decorateFilters();shop.querySelectorAll('.v788-card').forEach(decorateCard);emptyState();return true}
 function schedule(ms=45,force=false){if(scheduled)return;scheduled=true;setTimeout(()=>decorate(force),ms)}
 function setView(v){if(!VIEWS.some(x=>x[0]===v))v='all';view=v;lastSig='';decorate(true);return view}
 function previewCard(card){const x=cardItem(card);if(!x||status(x)==='equipped')return false;try{return PREVIEW?.open?.(x.id)!==false}catch(e){return false}}
 document.addEventListener('click',e=>{const vb=e.target.closest?.('[data-v791-view]');if(vb){e.preventDefault();e.stopPropagation();setView(vb.dataset.v791View);return}const card=e.target.closest?.('#worldScreenBody .v788-card');if(!card||e.target.closest('button'))return;if(previewCard(card)){card.classList.remove('v791-card-pulse');void card.offsetWidth;card.classList.add('v791-card-pulse')}},true);
 document.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key))return;const card=e.target.closest?.('#worldScreenBody .v788-card.v791-previewable');if(!card||e.target.closest('button'))return;e.preventDefault();previewCard(card)},true);
 const obs=new MutationObserver(ms=>{for(const m of ms){if(m.target?.closest?.('.v791-shop-polish,.v791-state,.v791-empty'))continue;if(m.type==='childList'&&m.target?.closest?.('#worldScreenBody')){schedule(55,false);break}}});obs.observe(document.body,{childList:true,subtree:true});
 document.addEventListener('click',e=>{if(e.target.closest?.('[data-v788-filter],[data-v788-buy],[data-v788-use],[data-v789-mode],.v789-cancel,.v789-preview-close,[data-v790-apply]')){schedule(180,false)}},false);
 document.addEventListener('visibilitychange',()=>{if(!document.hidden){schedule(120,false)}});window.addEventListener('pageshow',()=>{schedule(140,false)});
 state.stateVersion=Math.max(STATE_VERSION,Number(state.stateVersion)||0);try{saveState?.()}catch(e){}
 window.DEEN_WORLD_SHOP_POLISH={version:VERSION,stateVersion:STATE_VERSION,refresh:()=>decorate(true),setView,snapshot:()=>({version:VERSION,view,gold:gold(),level:level(),counts:counts(),cards:document.querySelectorAll('#worldScreenBody .v788-card').length,visibleCards:[...document.querySelectorAll('#worldScreenBody .v788-card')].filter(c=>!c.classList.contains('v791-hidden')).length,overview:!!document.querySelector('#worldScreenBody .v791-shop-polish')})};
 setTimeout(()=>decorate(true),850);
})();
