(()=>{
 if(window.__deenV792Applied)return;window.__deenV792Applied=true;
 const VERSION='7.9.2',STATE_VERSION=65;
 window.DEEN_RELEASE_VERSION=VERSION;document.title='DEEN v7.9.2 — Economy & Progression Balance';
 const PROG=window.DEEN_WORLD_PROGRESSION,COLLECTION=window.DEEN_WORLD_COLLECTION,LEVELUP=window.DEEN_WORLD_LEVELUP,EVOLUTION=window.DEEN_WORLD_EVOLUTION,SHOP=window.DEEN_WORLD_SHOP_POLISH;
 if(!PROG)return;
 const LEVELS=[
  {n:1,min:0,title:'Başlangıç',bonus:0},
  {n:2,min:25,title:'Yeşeren Köşe',unlock:'plant_olive',bonus:6},
  {n:3,min:70,title:'Okuma Alanı',unlock:'shelf_oak',bonus:10},
  {n:4,min:130,title:'Sıcak Dokunuş',unlock:'rug_sunrise',bonus:15},
  {n:5,min:205,title:'Odak Alanı',unlock:'desk_sand',bonus:20},
  {n:6,min:295,title:'Gece Manzarası',unlock:'window_night',bonus:25},
  {n:7,min:400,title:'Yıldız Işığı',unlock:'nur_starlight',bonus:30}
 ];
 const DAILY={visit:{nur:5,gold:4},interact:{nur:8,gold:6},lesson:{nur:12,gold:8}};
 const DAILY_TOTAL={nur:25,gold:18};
 const PRICE_BANDS={common:[35,75],rare:[55,120],epic:[130,170]};
 const oldSnapshot=PROG.snapshot?.bind(PROG),oldTasks=PROG.tasks?.bind(PROG);
 let scheduled=false;
 function clone(v){return JSON.parse(JSON.stringify(v))}
 function save(){try{saveState?.()}catch(e){}}
 function syncLegacy(){try{oldSnapshot?.()}catch(e){};state.myWorld=state.myWorld&&typeof state.myWorld==='object'?state.myWorld:{};state.myWorld.progression=state.myWorld.progression&&typeof state.myWorld.progression==='object'?state.myWorld.progression:{};const p=state.myWorld.progression;p.nur=Math.max(0,Number(p.nur)||0);p.levelClaims=Array.isArray(p.levelClaims)?p.levelClaims:[];p.daily=p.daily&&typeof p.daily==='object'?p.daily:{date:'',visited:false,items:[],claimed:[]};p.daily.claimed=Array.isArray(p.daily.claimed)?p.daily.claimed:[];state.myWorld.progressionBalance=state.myWorld.progressionBalance&&typeof state.myWorld.progressionBalance==='object'?state.myWorld.progressionBalance:{};state.myWorld.progressionBalance.version=VERSION;state.myWorld.progressionBalance.dailyTotal={...DAILY_TOTAL};state.myWorld.progressionBalance.levelThresholds=LEVELS.map(x=>x.min);state.stateVersion=Math.max(STATE_VERSION,Number(state.stateVersion)||0);return p}
 function levelFor(nur=syncLegacy().nur){let cur=LEVELS[0];for(const l of LEVELS)if(nur>=l.min)cur=l;return cur}
 function nextLevel(nur=syncLegacy().nur){const cur=levelFor(nur);return LEVELS.find(x=>x.n===cur.n+1)||null}
 function taskList(){let a=[];try{a=oldTasks?.()||[]}catch(e){};return a.map(t=>({...t,nur:DAILY[t.id]?.nur??t.nur,gold:DAILY[t.id]?.gold??t.gold}))}
 function progress(){const p=syncLegacy(),cur=levelFor(p.nur),next=nextLevel(p.nur);if(!next)return{cur,next:null,pct:100,left:0,nur:p.nur};const span=Math.max(1,next.min-cur.min),within=Math.max(0,p.nur-cur.min);return{cur,next,pct:Math.max(0,Math.min(100,within/span*100)),left:Math.max(0,next.min-p.nur),nur:p.nur}}
 function pendingCount(){const p=syncLegacy(),daily=taskList().filter(x=>x.done&&!x.claimed).length,lv=LEVELS.filter(x=>x.n>1&&x.n<=levelFor(p.nur).n&&!p.levelClaims.includes(x.n)).length;return daily+lv}
 function addGold(n,reason,key){n=Math.max(0,Math.round(Number(n)||0));state.currency=Math.max(0,Number(state.currency)||0)+n;state.myWorld.ledger=Array.isArray(state.myWorld.ledger)?state.myWorld.ledger:[];state.myWorld.ledger.push({at:Date.now(),type:'earn',amount:n,reason,key});if(state.myWorld.ledger.length>120)state.myWorld.ledger=state.myWorld.ledger.slice(-120);return n}
 function afterReward(beforeLevel){const after=levelFor().n;save();try{updateUI?.()}catch(e){};decorate(true);try{SHOP?.refresh?.()}catch(e){};try{EVOLUTION?.apply?.(true)}catch(e){};if(after>beforeLevel)setTimeout(()=>{try{LEVELUP?.show?.(after)}catch(e){}},140);return after}
 function claimDaily(id){const p=syncLegacy(),t=taskList().find(x=>x.id===id),reward=DAILY[id];if(!reward||!t||!t.done||t.claimed||p.daily.claimed.includes(id))return false;const before=levelFor(p.nur).n;p.daily.claimed.push(id);p.nur+=reward.nur;addGold(reward.gold,'world_daily_balanced',(p.daily.date||'today')+':'+id);afterReward(before);try{DEEN_SFX?.play?.('reward')}catch(e){};toast?.('+'+reward.nur+' NUR · +'+reward.gold+' Altın');return true}
 function claimLevel(n){const p=syncLegacy(),l=LEVELS.find(x=>x.n===Number(n)),cur=levelFor(p.nur);if(!l||l.n<=1||cur.n<l.n||p.levelClaims.includes(l.n))return false;p.levelClaims.push(l.n);addGold(l.bonus,'world_level_balanced','level:'+l.n);save();try{updateUI?.()}catch(e){};decorate(true);try{SHOP?.refresh?.()}catch(e){};try{DEEN_SFX?.play?.('reward')}catch(e){};toast?.('Oda Seviye '+l.n+' ödülü · +'+l.bonus+' Altın');return true}
 function itemMap(){try{return Object.fromEntries((COLLECTION?.items?.()||window.DEEN_WORLD?.items?.()||[]).map(x=>[x.id,x]))}catch(e){return{}}}
 function closePanel(){document.querySelector('.v780-sheet.v784-progression-sheet')?.remove();document.body.classList.remove('v780-sheet-open')}
 function questMarkup(){return taskList().map(t=>`<div class="v784-quest ${t.done?'done ':''}${t.claimed?'claimed':''}"><span class="v784-quest-ico">${t.icon}</span><span class="v784-quest-copy"><b>${t.title}</b><small>${t.copy} · ${t.value}/${t.target}</small><small class="reward">✦ +${t.nur} NUR · 🪙 +${t.gold} Altın</small></span><button class="v784-quest-btn" data-v792-daily="${t.id}" ${!t.done||t.claimed?'disabled':''}>${t.claimed?'ALINDI':t.done?'AL':'DEVAM'}</button></div>`).join('')}
 function roadMarkup(){const p=syncLegacy(),cur=levelFor(p.nur),items=itemMap();return LEVELS.slice(1).map(l=>{const unlocked=cur.n>=l.n,claimed=p.levelClaims.includes(l.n),it=items[l.unlock]||{name:l.unlock,price:0};let side;if(!unlocked)side=`<span class="v784-road-side">🔒 ${l.min} NUR</span>`;else if(!claimed)side=`<button class="v784-road-claim" data-v792-level="${l.n}">+${l.bonus} ALTIN · AL</button>`;else side='<span class="v784-road-side unlocked">AÇIK ✓</span>';return `<div class="v784-road-row ${unlocked?'current':'locked'}"><span class="v784-road-lv">LV ${l.n}</span><span class="v784-road-copy"><b>${it.name||l.unlock}</b><small>${l.title} · mağazada açılır · 🪙 ${Number(it.price)||0}</small></span>${side}</div>`}).join('')}
 function openPanel(){try{window.DEEN_WORLD_SIMPLE?.closeSheet?.()}catch(e){};closePanel();const p=syncLegacy(),lp=progress(),o=document.createElement('div');o.className='v780-sheet v784-progression-sheet v792-balance-sheet';o.innerHTML=`<div class="v780-sheet-card" role="dialog" aria-modal="true"><div class="v780-grab"></div><div class="v780-sheet-head"><div><b>Oda Yolculuğu</b><small>Dengeli günlük ritim ve kozmetik ilerleme</small></div><button class="v780-close" type="button" aria-label="Kapat">×</button></div><div class="v784-sheet-copy"><div class="v784-summary"><span class="v784-summary-level">LV<br>${lp.cur.n}</span><span class="v784-summary-copy"><b>${lp.cur.title}</b><small>✦ ${p.nur} NUR${lp.next?' · sonraki seviyeye '+lp.left:' · maksimum seviye'}</small><span class="v784-summary-bar"><i style="width:${lp.pct.toFixed(1)}%"></i></span></span></div><div class="v792-balance-note"><span><b>GÜNLÜK MAKS.</b> ✦ ${DAILY_TOTAL.nur} NUR · 🪙 ${DAILY_TOTAL.gold} Altın</span><span>LV 7 ≈ 16 tam aktif gün</span></div><div class="v784-section-title"><b>Bugünün görevleri</b><small>${taskList().filter(x=>x.done).length}/3 tamamlandı</small></div><div class="v784-quests">${questMarkup()}</div><div class="v784-section-title"><b>Seviye kilitleri</b><small>Dekor + tek seferlik Altın</small></div><div class="v784-road">${roadMarkup()}</div><div class="v792-price-note"><b>Fiyat ritmi</b><span>Common ${PRICE_BANDS.common[0]}–${PRICE_BANDS.common[1]} · Rare ${PRICE_BANDS.rare[0]}–${PRICE_BANDS.rare[1]} · Epic ${PRICE_BANDS.epic[0]}–${PRICE_BANDS.epic[1]} Altın</span></div><div class="v784-note"><b>NUR</b> yalnızca Dünyam için kozmetik ilerleme puanıdır; dinî yeterlilik, ibadet veya maneviyat ölçüsü değildir.</div></div></div>`;o.addEventListener('click',e=>{const d=e.target.closest?.('[data-v792-daily]');if(d){claimDaily(d.dataset.v792Daily);return}const l=e.target.closest?.('[data-v792-level]');if(l){claimLevel(Number(l.dataset.v792Level));return}if(e.target===o||e.target.closest('.v780-close'))closePanel()});document.body.append(o);document.body.classList.add('v780-sheet-open');return true}
 function decorateStrip(){const el=document.querySelector('#worldScreenBody .v784-progress-strip');if(!el)return false;const p=syncLegacy(),lp=progress(),done=taskList().filter(x=>x.done).length,pending=pendingCount(),badge=el.querySelector('.v784-level-badge'),copy=el.querySelector('.v784-progress-copy'),side=el.querySelector('.v784-progress-side'),bar=el.querySelector('.v784-progress-bar i');if(badge)badge.innerHTML='ODA<br>LV '+lp.cur.n;if(copy)copy.innerHTML=`<b>${lp.cur.title}</b><small>✦ ${p.nur}${lp.next?' / '+lp.next.min:''} NUR · ${done}/3 günlük görev</small>`;if(side){side.textContent=pending?pending+' ÖDÜL':'DETAY ›';side.classList.toggle('reward',!!pending)}if(bar)bar.style.width=lp.pct.toFixed(1)+'%';el.dataset.v792='1';return true}
 function decorate(force=false){scheduled=false;syncLegacy();decorateStrip();if(document.querySelector('.v792-balance-sheet')&&force)openPanel();return true}
 function schedule(ms=55){if(scheduled)return;scheduled=true;setTimeout(()=>decorate(false),ms)}
 PROG.claimDaily=claimDaily;PROG.claimLevel=claimLevel;PROG.open=openPanel;PROG.level=()=>clone(levelFor());PROG.tasks=()=>clone(taskList());PROG.snapshot=()=>{const p=syncLegacy(),lp=progress();return clone({version:VERSION,nur:p.nur,level:lp.cur.n,next:lp.next?.n||null,daily:p.daily,tasks:taskList(),pending:pendingCount(),gold:Number(state.currency)||0,locks:Object.fromEntries(LEVELS.filter(x=>x.unlock).map(x=>[x.unlock,x.n])),balance:{daily:{...DAILY_TOTAL},levels:LEVELS.map(x=>({n:x.n,min:x.min,bonus:x.bonus})),priceBands:PRICE_BANDS}})};
 document.addEventListener('click',e=>{const strip=e.target.closest?.('#worldScreenBody .v784-progress-strip');if(strip){e.preventDefault();e.stopImmediatePropagation();openPanel();return}if(e.target.closest?.('[data-v788-buy],[data-v789-mode],.navbtn[data-screen="worldScreen"]'))schedule(180)},true);
 const obs=new MutationObserver(ms=>{for(const m of ms){if(m.target?.closest?.('.v792-balance-sheet,.v792-balance-note,.v792-price-note'))continue;if(m.type==='childList'&&m.target?.closest?.('#worldScreenBody')){schedule(70);break}}});obs.observe(document.body,{childList:true,subtree:true});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule(120)});window.addEventListener('pageshow',()=>schedule(150));
 syncLegacy();save();
 window.DEEN_WORLD_BALANCE={version:VERSION,stateVersion:STATE_VERSION,levels:()=>clone(LEVELS),daily:()=>clone(DAILY),priceBands:()=>clone(PRICE_BANDS),refresh:()=>decorate(true),open:openPanel,snapshot:()=>PROG.snapshot()};
 setTimeout(()=>{decorateStrip();try{SHOP?.refresh?.()}catch(e){}},850);
})();
