(()=>{
 if(window.__deenV820Applied)return;window.__deenV820Applied=true;
 const VERSION='8.2.0',STATE_VERSION=72;
 window.DEEN_RELEASE_VERSION=VERSION;document.title='DEEN v8.2.0 — Room & Shop Refresh';
 const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
 const WORLD=window.DEEN_WORLD,COL=window.DEEN_WORLD_COLLECTION,DECOR=window.DEEN_WORLD_DECOR,PRE=window.DEEN_WORLD_PREVIEW,PRESETS=window.DEEN_WORLD_PRESETS,PROG=window.DEEN_WORLD_PROGRESSION;
 if(!WORLD||!COL||!DECOR)return;
 const CATS=[['all','Tümü'],['desk','Masa'],['rug','Halı'],['plant','Bitki'],['shelf','Kitaplık'],['window','Pencere'],['nur','NUR']];
 const BASE={desk:{id:null,name:'Standart Masa',desc:'Odanın varsayılan çalışma masası.'},rug:{id:'rug_teal',name:'Teal Halı',desc:'Başlangıç halısı.'},plant:{id:null,name:'Bitki Yok',desc:'Bitkiyi odadan kaldır.'},shelf:{id:null,name:'Kitaplık Yok',desc:'Kitaplığı odadan kaldır.'},window:{id:null,name:'Standart Pencere',desc:'Varsayılan oda penceresi.'},nur:{id:null,name:'Standart NUR',desc:'Varsayılan ışık görünümü.'}};
 let roomCat='desk',shopCat='all',shopView='all',lastFocus=null;
 function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function items(){try{return COL.items?.()||[]}catch(e){return[]}}
 function snap(){try{return COL.snapshot?.()||{}}catch(e){return{}}}
 function eq(){return snap().equipped||state.myWorld?.equipped||{}}
 function ownedIds(){return new Set(snap().owned||state.myWorld?.owned||[])}
 function level(){return Number(snap().level||PROG?.snapshot?.().level||1)||1}
 function gold(){return Number(state.currency)||0}
 function item(id){return items().find(x=>x.id===id)||null}
 function rarity(x){return String(x?.rarity||'common').toLowerCase()}
 function typeName(t){return ({desk:'Masa',rug:'Halı',plant:'Bitki',shelf:'Kitaplık',window:'Pencere',nur:'NUR'})[t]||t}
 function isOwned(x){return !x?.id || x.id==='rug_teal' || ownedIds().has(x.id)}
 function isEquipped(x){return Object.prototype.hasOwnProperty.call(eq(),x.type)&&eq()[x.type]===x.id}
 function canBuy(x){return !isOwned(x)&&level()>=(Number(x.req)||1)&&gold()>=(Number(x.price)||0)}
 function roomNode(){return document.getElementById('v750Room')}
 function cloneRoom(){const r=roomNode();if(!r)return null;const c=r.cloneNode(true);c.removeAttribute('id');c.querySelectorAll('[id]').forEach(n=>n.removeAttribute('id'));c.querySelectorAll('button,input,[tabindex]').forEach(n=>n.setAttribute('tabindex','-1'));return c}
 function refreshRoomClone(){const host=$('#v820RoomOverlay .v820-room-preview');if(!host)return;const c=cloneRoom();host.innerHTML='';if(c)host.append(c);host.insertAdjacentHTML('beforeend','<span class="v820-room-label">CANLI ODA</span>')}
 function thumbClass(x){return x?.id?x.type:'base'}
 function baseItem(type){return {...BASE[type],type,rarity:'starter',req:1,price:0,base:true}}
 function roomList(type){return [baseItem(type),...items().filter(x=>x.type===type&&!x.paid&&!x.default)]}
 function cardRoom(x){const own=isOwned(x),sel=isEquipped(x),locked=!own&&level()<(Number(x.req)||1);return `<article class="v820-decor ${sel?'selected':''} ${locked?'locked':''}" data-id="${x.id||''}" data-type="${x.type}"><div class="v820-decor-thumb ${thumbClass(x)}"></div><h3>${esc(x.name)}</h3><p>${esc(x.desc||'Dünyam için kalıcı kozmetik dekor.')}</p><div class="v820-decor-meta"><span class="v820-rarity ${rarity(x)}">${x.base?'BAŞLANGIÇ':rarity(x).toUpperCase()}</span><span class="${own?'v820-owned':'v820-price'}">${own?'Sende':'🪙 '+(Number(x.price)||0)}</span></div><div class="v820-mini-actions">${own?`<button class="primary" data-v820-equip="${x.id??'__base__'}" data-type="${x.type}" ${sel?'disabled':''}>${sel?'Kullanılıyor':'Kullan'}</button>`:`<button data-v820-preview="${x.id}" ${locked?'disabled':''}>Önizle</button><button class="gold" data-v820-buy="${x.id}" ${locked?'disabled':''}>${locked?'LV '+(x.req||1):'Satın Al'}</button>`}</div></article>`}
 function renderRoomRail(){const rail=$('#v820RoomOverlay .v820-rail');if(rail)rail.innerHTML=roomList(roomCat).map(cardRoom).join('');$$('#v820RoomOverlay .v820-cat').forEach(b=>b.classList.toggle('active',b.dataset.cat===roomCat));renderPresets();refreshRoomClone();updateRoomWallet()}
 function renderPresets(){const box=$('#v820RoomOverlay .v820-presets');if(!box||!PRESETS)return;let slots=[];try{slots=PRESETS.slots?.()||[]}catch(e){};const active=PRESETS.snapshot?.().active;box.innerHTML=slots.map(s=>`<button class="v820-preset ${s.snapshot?'saved':''} ${active===s.id?'active':''}" data-slot="${s.id}"><b>${s.id==='work'?'Çalışma':s.id==='night'?'Gece':'Doğa'}</b><small>${s.snapshot?'Dokun: uygula · Basılı: güncelle':'Dokun: bu odayı kaydet'}</small></button>`).join('')}
 function updateRoomWallet(){const w=$('#v820RoomOverlay .v820-wallet');if(w)w.textContent='🪙 '+gold()+' Altın'}
 function mountRoom(){let o=document.getElementById('v820RoomOverlay');if(o)return o;o=document.createElement('div');o.id='v820RoomOverlay';o.innerHTML=`<div class="v820-sheet"><div class="v820-head"><button class="v820-back" data-close>‹ Geri</button><div class="v820-headcopy"><small>BENİM DÜNYAM</small><b>Oda Düzeni</b><span>Dekorlarını seç, kombinlerini kaydet.</span></div><button class="v820-done" data-close>Bitti</button></div><div class="v820-room-preview-wrap"><div class="v820-room-preview"></div></div><div class="v820-presets"></div><div class="v820-catbar">${CATS.filter(x=>x[0]!=='all').map(([id,n])=>`<button class="v820-cat ${id===roomCat?'active':''}" data-cat="${id}">${n}</button>`).join('')}</div><div class="v820-rail"></div><div class="v820-note"><b>İpucu:</b> Sahip olduğun dekoru seçtiğinde oda anında güncellenir. Presetler Altın harcamaz.</div></div>`;document.body.append(o);o.addEventListener('click',roomClick);o.addEventListener('pointerdown',presetHoldStart);o.addEventListener('pointerup',presetHoldEnd);o.addEventListener('pointercancel',presetHoldEnd);return o}
 let holdTimer=null,held=false;
 function presetHoldStart(e){const b=e.target.closest('.v820-preset');if(!b)return;held=false;clearTimeout(holdTimer);holdTimer=setTimeout(()=>{held=true;try{PRESETS?.save?.(b.dataset.slot);setTimeout(renderRoomRail,80)}catch(_){}},650)}
 function presetHoldEnd(){clearTimeout(holdTimer)}
 function roomClick(e){if(e.target===e.currentTarget||e.target.closest('[data-close]')){closeRoom();return}const cat=e.target.closest('[data-cat]');if(cat){roomCat=cat.dataset.cat;renderRoomRail();return}const p=e.target.closest('.v820-preset');if(p){if(held){held=false;return}const slots=PRESETS?.slots?.()||[],s=slots.find(x=>x.id===p.dataset.slot);try{s?.snapshot?PRESETS.apply?.(p.dataset.slot):PRESETS.save?.(p.dataset.slot)}catch(_){}setTimeout(renderRoomRail,100);return}const eqb=e.target.closest('[data-v820-equip]');if(eqb){const type=eqb.dataset.type,id=eqb.dataset.v820Equip==='__base__'?BASE[type].id:eqb.dataset.v820Equip;try{DECOR.equip?.(type,id)}catch(_){}setTimeout(renderRoomRail,100);return}const buy=e.target.closest('[data-v820-buy]');if(buy){try{WORLD.buy?.(buy.dataset.v820Buy)}catch(_){}setTimeout(renderRoomRail,160);return}const prev=e.target.closest('[data-v820-preview]');if(prev){closeRoom(false);setTimeout(()=>{try{PRE?.open?.(prev.dataset.v820Preview)}catch(_){}},30)}}
 function openRoom(){lastFocus=document.activeElement;mountRoom();const o=document.getElementById('v820RoomOverlay');o.classList.add('open');document.body.style.overflow='hidden';renderRoomRail();return true}
 function closeRoom(restore=true){const o=document.getElementById('v820RoomOverlay');o?.classList.remove('open');if(restore)document.body.style.overflow='';try{lastFocus?.focus?.()}catch(_){}return true}
 function shopItems(){return items().filter(x=>!x.paid&&!x.default)}
 function viewMatch(x){if(shopView==='owned')return isOwned(x);if(shopView==='equipped')return isEquipped(x);if(shopView==='buyable')return !isOwned(x)&&level()>=(Number(x.req)||1);return true}
 function filteredShop(){return shopItems().filter(x=>(shopCat==='all'||x.type===shopCat)&&viewMatch(x))}
 function shopCard(x){const own=isOwned(x),sel=isEquipped(x),locked=!own&&level()<(Number(x.req)||1);return `<article class="v820-shop-card ${sel?'equipped':''} ${locked?'locked':''}"><div class="v820-decor-thumb ${thumbClass(x)}"></div><h3>${esc(x.name)}</h3><p>${esc(x.desc||'Dünyam için kalıcı kozmetik dekor.')}</p><div class="v820-decor-meta"><span class="v820-rarity ${rarity(x)}">${rarity(x).toUpperCase()} · LV ${Number(x.req)||1}</span><span class="${own?'v820-owned':'v820-price'}">${own?'Sende':'🪙 '+(Number(x.price)||0)}</span></div><div class="v820-mini-actions"><button data-v820-shop-preview="${x.id}">Önizle</button>${own?`<button class="primary" data-v820-shop-use="${x.id}" ${sel?'disabled':''}>${sel?'Odada':'Kullan'}</button>`:`<button class="gold" data-v820-shop-buy="${x.id}" ${locked?'disabled':''}>${locked?'LV '+(x.req||1):'Satın Al'}</button>`}</div></article>`}
 function renderShop(){const list=filteredShop(),grid=$('#v820ShopOverlay .v820-shop-grid');if(grid)grid.innerHTML=list.length?list.map(shopCard).join(''):'<div class="v820-empty">Bu filtrede gösterilecek dekor yok.</div>';$$('#v820ShopOverlay .v820-cat').forEach(b=>b.classList.toggle('active',b.dataset.shopcat===shopCat));$$('#v820ShopOverlay .v820-view').forEach(b=>b.classList.toggle('active',b.dataset.view===shopView));const all=shopItems(),own=all.filter(isOwned).length,pct=all.length?Math.round(own/all.length*100):0;const txt=$('#v820ShopOverlay [data-summary]');if(txt)txt.innerHTML=`<b>${own}/${all.length} dekor sende</b><small>Oda Seviyesi ${level()} · Koleksiyon %${pct}</small><div class="v820-summary-progress"><i style="width:${pct}%"></i></div>`;const w=$('#v820ShopOverlay .v820-wallet');if(w)w.textContent='🪙 '+gold()+' Altın'}
 function mountShop(){let o=document.getElementById('v820ShopOverlay');if(o)return o;o=document.createElement('div');o.id='v820ShopOverlay';o.innerHTML=`<div class="v820-sheet"><div class="v820-head"><button class="v820-back" data-close>‹ Odaya Dön</button><div class="v820-headcopy"><small>DÜNYA MAĞAZASI</small><b>Dekor Koleksiyonu</b><span>Önizle, satın al ve odanda kullan.</span></div><span class="v820-wallet">🪙 0 Altın</span></div><div class="v820-shop-summary"><div class="v820-summary-card"><div data-summary></div><button class="v820-done" data-open-room>Oda Düzeni</button></div></div><div class="v820-viewbar">${[['all','Tümü'],['buyable','Alınabilir'],['owned','Sahip'],['equipped','Odada']].map(([id,n])=>`<button class="v820-view ${id===shopView?'active':''}" data-view="${id}">${n}</button>`).join('')}</div><div class="v820-catbar">${CATS.map(([id,n])=>`<button class="v820-cat ${id===shopCat?'active':''}" data-shopcat="${id}">${n}</button>`).join('')}</div><div class="v820-shop-grid"></div><div class="v820-note">Altın yalnızca dünya, kıyafet ve kozmetik için kullanılır. Altınla enerji satın alınamaz.</div></div>`;document.body.append(o);o.addEventListener('click',shopClick);return o}
 function shopClick(e){if(e.target===e.currentTarget||e.target.closest('[data-close]')){closeShop();return}if(e.target.closest('[data-open-room]')){closeShop(false);openRoom();return}const v=e.target.closest('[data-view]');if(v){shopView=v.dataset.view;renderShop();return}const c=e.target.closest('[data-shopcat]');if(c){shopCat=c.dataset.shopcat;renderShop();return}const prev=e.target.closest('[data-v820-shop-preview]');if(prev){closeShop(false);setTimeout(()=>{try{PRE?.open?.(prev.dataset.v820ShopPreview)}catch(_){}},30);return}const use=e.target.closest('[data-v820-shop-use]');if(use){try{COL.equip?.(use.dataset.v820ShopUse)}catch(_){}setTimeout(renderShop,100);return}const buy=e.target.closest('[data-v820-shop-buy]');if(buy){try{WORLD.buy?.(buy.dataset.v820ShopBuy)}catch(_){}setTimeout(renderShop,180)}}
 function openShop(){lastFocus=document.activeElement;mountShop();document.getElementById('v820ShopOverlay').classList.add('open');document.body.style.overflow='hidden';renderShop();return true}
 function closeShop(restore=true){document.getElementById('v820ShopOverlay')?.classList.remove('open');if(restore)document.body.style.overflow='';try{lastFocus?.focus?.()}catch(_){}return true}
 document.addEventListener('click',e=>{if(e.target.closest?.('[data-v810-toggle-edit]')){e.preventDefault();e.stopImmediatePropagation();openRoom();return}if(e.target.closest?.('[data-v810-open-shop]')){e.preventDefault();e.stopImmediatePropagation();openShop();return}},true);
 document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(document.getElementById('v820RoomOverlay')?.classList.contains('open'))closeRoom();else if(document.getElementById('v820ShopOverlay')?.classList.contains('open'))closeShop()});
 const oldTab=WORLD.tab?.bind(WORLD);if(oldTab&&!WORLD.__v820tab){WORLD.tab=function(t,...a){if(t==='shop')return openShop();return oldTab(t,...a)};WORLD.__v820tab=true}
 state.stateVersion=Math.max(STATE_VERSION,Number(state.stateVersion)||0);try{saveState?.()}catch(e){}
 window.DEEN_WORLD_ROOM_UI={version:VERSION,open:openRoom,close:closeRoom,refresh:renderRoomRail,snapshot:()=>({version:VERSION,category:roomCat,open:!!document.getElementById('v820RoomOverlay')?.classList.contains('open'),equipped:{...eq()},presets:PRESETS?.slots?.()||[]})};
 window.DEEN_WORLD_SHOP_UI={version:VERSION,open:openShop,close:closeShop,refresh:renderShop,snapshot:()=>({version:VERSION,category:shopCat,view:shopView,open:!!document.getElementById('v820ShopOverlay')?.classList.contains('open'),gold:gold(),level:level(),items:filteredShop().length})};
})();
