(()=>{
 if(window.__deenV832HF2JCloset)return;window.__deenV832HF2JCloset=true;
 const VERSION='8.3.2-HF2J',REV='832hf2j1';
 const $=(s,r=document)=>r?.querySelector?.(s)||null,$$=(s,r=document)=>[...(r?.querySelectorAll?.(s)||[])];
 const LEGACY=['outfit_teal','outfit_lavender','outfit_navy','outfit_cream'];
 const NAMES=['Teal Tunik','Lavanta Tunik','Lacivert Tunik','Krem Tunik'];
 const CFG={male:{count:12,cell:96,cols:6,file:'male_atlas.b64'},female:{count:11,cell:80,cols:6,file:'female_atlas.b64'}};
 const URLS={male:'',female:''},preview={male:null,female:null},initial={male:null,female:null};
 const SAFE='./assets/visual-runtime/wear_outfits.webp?v=8321';
 function studio(){return window.DEEN_AVATAR_STUDIO} function pro(){return window.DEEN_WARDROBE_PRO} function world(){return window.DEEN_WORLD} function avatar(){return window.DEEN_AVATAR_ASSETS}
 function g(){try{return studio()?.state?.().gender==='male'?'male':'female'}catch(_){return 'female'}}
 function ws(){try{return world()?.snapshot?.()||{}}catch(_){return {}}} function items(){try{return world()?.items?.()||[]}catch(_){return []}}
 function idFor(x,i){return `${x}_${String(i+1).padStart(2,'0')}`} function idx(x,id){const m=String(id||'').match(new RegExp(`^${x}_(\\d{2})$`));if(!m)return null;const n=+m[1]-1;return n>=0&&n<CFG[x].count?n:null}
 function legacyEq(){return ws()?.equipped?.outfit||'outfit_teal'} function legacyIdx(){const n=LEGACY.indexOf(legacyEq());return n<0?0:n}
 function store(){try{state.myWorld=state.myWorld&&typeof state.myWorld==='object'?state.myWorld:{};state.myWorld.avatarAssets=state.myWorld.avatarAssets&&typeof state.myWorld.avatarAssets==='object'?state.myWorld.avatarAssets:{};const a=state.myWorld.avatarAssets;a.visualOutfit=a.visualOutfit&&typeof a.visualOutfit==='object'?a.visualOutfit:{};return a.visualOutfit}catch(_){return {}}}
 function saved(x){const s=store();return idx(x,s[x])!==null?s[x]:idFor(x,legacyIdx())} function current(x=g()){return idx(x,preview[x])!==null?preview[x]:saved(x)}
 function atlasStyle(x,id){const i=idx(x,id),c=CFG[x];if(i===null||!URLS[x])return '';const rows=Math.ceil(c.count/c.cols),aw=c.cols*c.cell,ah=rows*c.cell,col=i%c.cols,row=Math.floor(i/c.cols),px=aw===c.cell?0:(col*c.cell/(aw-c.cell))*100,py=ah===c.cell?0:(row*c.cell/(ah-c.cell))*100;return `background-image:url('${URLS[x]}');background-size:${(aw/c.cell)*100}% ${(ah/c.cell)*100}%;background-position:${px}% ${py}%;background-repeat:no-repeat;`}
 function safeStyle(x,i){const y=x==='male'?112:0,xx=i*112;return `background-image:url('${SAFE}');background-size:400% 200%;background-position:${xx/(448-112)*100}% ${y/(224-112)*100}%;background-repeat:no-repeat;`}
 async function load(x){const r=await fetch(`./assets/clothing-runtime/hf2e/${CFG[x].file}?v=${REV}`,{cache:'no-store'});if(!r.ok)throw new Error(`${x} atlas HTTP ${r.status}`);const t=(await r.text()).replace(/\s+/g,'');if(!t.startsWith('UklGR'))throw new Error(`${x} atlas invalid`);URLS[x]=`data:image/webp;base64,${t}`}
 function outfitMode(){try{const s=pro()?.snapshot?.();return s?.sub==='worldOutfit'||s?.cat==='outfit'}catch(_){return false}}
 function info(x,i){if(i<4){const it=items().find(o=>o?.id===LEGACY[i]),owned=new Set(ws()?.owned||[]);return {name:it?.name||NAMES[i],sub:(it?.default||owned.has(LEGACY[i]))?'SAHİPSİN':`🪙 ${Number(it?.price||0)}`}}return {name:`${x==='male'?'Erkek':'Kadın'} Kombin ${i+1}`,sub:'KATALOG'}}
 function cards(x){const cur=current(x);return Array.from({length:CFG[x].count},(_,i)=>{const id=idFor(x,i),m=info(x,i);return `<button type="button" class="v812-card v812-outfit v832j-card ${id===cur?'active':''}" data-v832j-real="${id}"><span class="ico v832i-thumb"><span class="v832i-sprite" style="${atlasStyle(x,id)}"></span></span><b>${m.name}</b><span class="price">${id===cur?'SEÇİLİ':m.sub}</span></button>`}).join('')}
 function ensureStack(){const root=$('#v812Wardrobe'),box=$('.v812-avatar',root);if(!root||!box||!outfitMode())return null;const x=g();try{const st=avatar()?.state?.();if(st?.gender!==x)avatar()?.setGender?.(x)}catch(_){};if(!$('.v831-stack',box)){try{const h=avatar()?.svg?.(x);if(h){box.innerHTML=h;box.classList.add('v832i-real-preview')}}catch(_){}}return $('.v831-stack',box)}
 function removeWear(stack){if(!stack)return;$$(':scope>.v832-worn-outfit,:scope>.v832d-worn-outfit,:scope>.v832e-worn-outfit,:scope>.v832f-worn-outfit,:scope>.v832g-worn-outfit,:scope>.v832h-worn-outfit,:scope>.v832i-worn-outfit,:scope>.v832j-worn-outfit',stack).forEach(n=>n.remove())}
 function wear(stack,x,id){if(!stack)return;removeWear(stack);const i=idx(x,id);if(i===null||i>3)return;const el=document.createElement('span');el.className='v831-sprite v832j-worn-outfit';el.dataset.v832jGender=x;el.style.cssText=safeStyle(x,i);const base=$(':scope>.layer-base_avatar',stack);base?base.after(el):stack.prepend(el)}
 function render(){const root=$('#v812Wardrobe');if(!root?.classList?.contains('open')||!outfitMode())return;const x=g(),grid=$('.v812-grid',root);if(!grid||!URLS[x])return;grid.innerHTML=cards(x);grid.classList.add('v832i-real-grid');let b=$('.v832i-runtime-badge',root);if(!b){b=document.createElement('span');b.className='v832i-runtime-badge';$('.v812-subtabs',root)?.insertAdjacentElement('afterend',b)}b.textContent='HF2J · REAL OUTFITS';wear(ensureStack(),x,current(x));}
 function choose(id){const x=g(),i=idx(x,id);if(i===null)return;preview[x]=id;render();if(i>3){const f=$('.v812-footcopy');if(f)f.innerHTML='<b>Kombin kataloğa eklendi</b><small>Bu kombin avatar uyarlaması bir sonraki adımda normalize edilecek.</small>'}}
 function commit(){const x=g(),id=current(x),i=idx(x,id);if(i===null)return false;if(i<4){const legacy=LEGACY[i],it=items().find(o=>o?.id===legacy),snap=ws(),owned=new Set(snap?.owned||[]),cost=Number(it?.price||0);if(!(it?.default||owned.has(legacy))&&Number(snap?.gold||0)<cost)return false;try{if(it?.default||owned.has(legacy))world()?.equip?.(legacy);else world()?.buy?.(legacy)}catch(_){return false}}const s=store();s[x]=id;try{saveState?.();updateUI?.()}catch(_){};initial[x]=id;return true}
 function applyWorld(){const x=g(),id=saved(x),i=idx(x,id);if(i===null||i>3)return;$$('[data-v831-real-avatar="1"].v831-stack').forEach(st=>{if(!st.closest?.('#v812Wardrobe'))wear(st,x,id)})}
 function tick(){const root=$('#v812Wardrobe');if(root?.classList?.contains('open')){const x=g();if(!initial[x])initial[x]=saved(x);if(preview[x]==null)preview[x]=initial[x];if(outfitMode())render()}else applyWorld()}
 document.addEventListener('click',e=>{const c=e.target.closest?.('[data-v832j-real]');if(c){e.preventDefault();e.stopImmediatePropagation();choose(c.dataset.v832jReal);return}if(e.target.closest?.('#v812Wardrobe [data-v812-save]')&&outfitMode()){e.preventDefault();e.stopImmediatePropagation();if(commit()){const r=$('#v812Wardrobe');r?.classList.remove('open');document.body.style.overflow='';setTimeout(()=>world()?.open?.('world'),80)}return}if(e.target.closest?.('#v812Wardrobe [data-v812-cat],#v812Wardrobe [data-v812-sub]')){setTimeout(tick,40);setTimeout(tick,140)}},true);
 Promise.all([load('male'),load('female')]).then(()=>{for(const x of ['male','female'])preview[x]=saved(x);setInterval(tick,150);[0,100,300,900].forEach(ms=>setTimeout(tick,ms));window.DEEN_REAL_CLOSET={version:VERSION,check:()=>({version:VERSION,gender:g(),cards:$$('#v812Wardrobe .v832j-card').length,current:current(),safeWear:idx(g(),current())<4})};window.DEEN_RELEASE_VERSION=VERSION;document.title='DEEN v8.3.2 HF2J'}).catch(err=>{window.DEEN_HF2J_ERROR=String(err?.message||err);console.error(err)});
})();